language: php
dist: trusty
php:
    - 5.6
    - 7.0
    - hhvm
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y ruby-dev
    - sudo apt-get install -y gem
    - sudo gem install compass
install:
    - composer install --profile --optimize-autoloader
script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
